# Generated by Django 2.1.3 on 2018-11-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year_pub',
            field=models.IntegerField(default=2018),
        ),
    ]
