# Generated by Django 2.1.3 on 2018-11-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_year_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBooks',
            fields=[
                ('books_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Books')),
                ('genre', models.CharField(max_length=20)),
            ],
            bases=('books.books',),
        ),
    ]
