# Generated by Django 2.1.3 on 2018-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_personalbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbooks',
            name='format',
            field=models.CharField(default='Hardcover Book', max_length=50),
        ),
    ]
