# Generated by Django 2.1.3 on 2018-11-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalBooks',
            new_name='Book',
        ),
    ]
