# Generated by Django 2.1.3 on 2018-11-09 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20181108_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.Media')),
                ('genre', models.CharField(max_length=20)),
                ('format', models.CharField(default='Blu-ray', max_length=50)),
            ],
            bases=('media.media',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.Media')),
                ('genre', models.CharField(max_length=20)),
                ('format', models.CharField(default='MP3', max_length=50)),
            ],
            bases=('media.media',),
        ),
    ]
