# Generated by Django 2.1.3 on 2018-11-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20181110_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='reviewer',
            new_name='user',
        ),
    ]
