# Generated by Django 2.1.3 on 2018-11-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_movies_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
