# Generated by Django 2.1.3 on 2018-11-09 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0005_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Reviewer',
        ),
    ]
