# Generated by Django 2.1.3 on 2018-11-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20181109_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='author',
            new_name='artist',
        ),
    ]
