# Generated by Django 2.1.3 on 2018-11-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20181109_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='user',
            new_name='username',
        ),
    ]
