# Generated by Django 2.1.3 on 2018-11-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20181109_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='username',
            new_name='user',
        ),
    ]
